name: Nightly run to create export of all Allmaps annotations in the iiif.digitalcommonwealth.org domain
on: 
  workflow_dispatch
jobs:
  nightly-download-allmaps-annotations:
    name: Write boston-volume-extents.geojson to production on Wasabi
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use cURL to download
        run: |-
          curl -o ./allmaps/annotations.json "https://annotations.allmaps.org/maps?imageservicedomain=iiif.digitalcommonwealth.org&key=${{ secrets.ALLMAPS_API_KEY }}&limit=-1"
      - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Allmaps data export: ${timestamp}" || exit 0
        git push