name: Write boston-volume-extents.geojson to production on Wasabi
on: 
  workflow_dispatch
jobs:
  upload-boston-volume-extents-to-wasabi:
    name: Write boston-volume-extents.geojson to production on Wasabi
    runs-on: ubuntu-latest
    steps:
      - name: Install s3cmd
        run: |
          pip3 install s3cmd
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest' 
      - name: Install topojson
        run: |
          npm install -g topojson-server
      - name: checkout
        uses: actions/checkout@v2
      - name: create topojson version of extents
        run: |
          geo2topo ./atlascope/atlascope-boston/boston-volume-extents.geojson > ./atlascope/atlascope-boston/boston-volume-extents.topojson
      - name: Run s3cmd to put geojson extents to Wasabi
        run: >
          s3cmd --host=s3.us-east-2.wasabisys.com --host-bucket="%(bucket)s.s3.wasabisys.com" --access_key=${{ secrets.WASABI_ACCESS_KEY_ID }} --secret_key=${{ secrets.WASABI_SECRET_KEY_ID }} put ./atlascope/atlascope-boston/boston-volume-extents.geojson s3://urbanatlases/extents/boston-volume-extents.geojson
      - name: Run s3cmd to put topojson extents to Wasabi
        run: >
          s3cmd --host=s3.us-east-2.wasabisys.com --host-bucket="%(bucket)s.s3.wasabisys.com" --access_key=${{ secrets.WASABI_ACCESS_KEY_ID }} --secret_key=${{ secrets.WASABI_SECRET_KEY_ID }} put ./atlascope/atlascope-boston/boston-volume-extents.topojson s3://urbanatlases/extents/boston-volume-extents.topojson
      - name: Run s3cmd to put coverage list to Wasabi
        run: >
          s3cmd --host=s3.us-east-2.wasabisys.com --host-bucket="%(bucket)s.s3.wasabisys.com" --access_key=${{ secrets.WASABI_ACCESS_KEY_ID }} --secret_key=${{ secrets.WASABI_SECRET_KEY_ID }} put ./atlascope/atlascope-boston/coverage-list.json s3://urbanatlases/extents/coverage-list.json
